version: "3.7"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "${MONGO_EXTERNAL_PORT}:${MONGO_PORT}"
    volumes:
      - /data/mongodb:/data/db

  ola-hd:
    build:
      context: code/
    command: java -Xms${OLA_HD_MIN_MEMORY} -Xmx${OLA_HD_MAX_MEMORY} -jar -Dspring.profiles.active=production --server.port=${OLA_HD_PORT} target/long-term-storage-0.0.1-SNAPSHOT.jar
    deploy:
      resources:
        limits:
          memory: 8GB
    ports:
      - "${OLA_HD_EXTERNAL_PORT}:${OLA_HD_PORT}"