version: "3.7"
services:
  mongo:
    image: mongo:4.0.10
    restart: on-failure
    volumes:
      - ~/ola-hd-data/mongodb:/data/db
    networks:
      - ola-hd
    env_file:
      - .env

  ola-hd:
    build:
      context: back-end/
    command: java -Xms${OLA_HD_MIN_MEMORY} -Xmx${OLA_HD_MAX_MEMORY} -jar -Dserver.port=${OLA_HD_PORT} target/long-term-storage-0.0.1-SNAPSHOT.jar
    deploy:
      resources:
        limits:
          memory: 8GB
    ports:
      - "${OLA_HD_EXTERNAL_PORT}:${OLA_HD_PORT}"
    depends_on:
      - mongo
    networks:
      - ola-hd
    env_file:
      - .env

  proxy:
    build:
      context: nginx/
    ports:
      - "80:80"
    depends_on:
      - ola-hd
    networks:
      - ola-hd

networks:
  ola-hd: